config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post '/users/sign_out' => 'devise/sessions#destroy'
  end
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'genres#index'

  resources :genres do
    resources :artists
  end

  resources :artists do
    resources :albums
  end

  resources :albums do
    resources :songs, only: [:index, :new, :create, :show, :destroy]
    resources :reviews, only: [:index, :new, :create, :show, :destroy]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :artists, dependent: :destroy
  has_many :albums, dependent: :destroy
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def index
    @genre = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Album.new(genre_params)
    @genre.save
    redirect_to genre_path(@genre)
  end

  def show
    @genre = Genre.find(params[:id])
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.paginate(page: params[:page], per_page: 5)
  end

  def show
    @artist = Artist.new
    @genre = Genre.find(params[:id])
    @genre_id = @genre.id
    @artists = Artist.where(genre_id: @genre_id).paginate(page: params[:page], per_page: 5)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Album.new(genre_params)
    @genre.save
    redirect_to genre_path(@genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/views/genres/index.html.erb
<h1>All of our genre</h1>

<% if current_user %>
  <h3>Login ID as <%= current_user.id  %></h3>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <%= link_to 'Log In', new_user_session_path  %>
<% end %>

<% @genres.each do |genre| %>
  <h3><%=link_to genre.genre_name, genre_path(genre)%>/total_artist:
      <%= genre.artists.count %>
  </h3>
<% end %>

<%= will_paginate @reviews %>

app/views/genres/new.html.erb
  <div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create new genre</h1>
      <%= simple_form_for @genre do |g| %>
        <%= g.input :name %>
        <%= g.button :submit, class: 'btn btn-light' %>
      <% end %>
      <div class=mt-3> <%= link_to "Back Home", root_path %> </div>
    </div>
  </div>
</div>

app/views/genres/show.html.erb
<h1>All Artist Of <%= @genre.genre_name %> </h1>

<% @artists.each do |a| %>
<h3><%= link_to a.name, artist_albums_path(a.id) %> / total_album:
  <%= a.albums.count  %></h3>
<% end %>

<%= will_paginate @artists %>

<%= render "artists/new", artist: @artist %>

<%= link_to 'Home', root_path %>