config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post '/users/sign_out' => 'devise/sessions#destroy'
  end
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'genres#index'

  resources :genres do
    resources :artists
  end

  resources :artists do
    resources :albums
  end

  resources :albums do
    resources :songs, only: [:index, :new, :create, :show, :destroy]
    resources :reviews, only: [:index, :new, :create, :show, :destroy]
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :songs, dependent: :destroy
  belongs_to :user
  belongs_to :genre
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
    before_action :set_album, only: [ :show, :edit, :update, :destroy]

  def index
    @genre = Genre.find(params[:genre_id])
    @albums = Album.all
  end

  def new
    @genre = Genre.find(params[:genre_id])
    @album = Album.new
  end

  def create
    @genre = Genre.find(params[:genre_id])
    @album = Album.new(album_params)
    @album.genre = @genre
    @album.save
    redirect_to genre_path(@genre)
  end

  def show
  end

  def edit
  end

  def update
    @album.update(album_params)
  end

  def destroy
    @album.destroy
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:name, :genre_name)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_artist, only: [:index, :new, :edit, :create, :update, :destroy]

  def index
    @albums = Album.where(artist_id: params[:artist_id])
    @album = Album.new
    # binding.pry
  end

  def new
    # binding.pry
    @album = Album.new
  end

  def create
    # binding.pry
    @genre_id = @artist.genre_id
    @album = Album.new(album_params)
    @album.user = current_user
    @album.artist_id = @artist.id
    @album.genre_id = @artist.genre_id
    # @artist_id = session[:artist_id]
    # @genre_id = session[:genre_id]
    # @id = @album.artist_id
    if @album.save
        redirect_to artist_albums_path(@artist)
    else
      binding.pry
    end
  end

  def show
    @album_id = params[:id]
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
    # binding.pry
  end

  def update
    if current_user.id != Album.find(params[:id]).user_id
      puts "You are not allowed for this action"
    else
      @album = Album.find(params[:id])
      if @album.update(album_params)
        redirect_to artist_albums_path(@artist)
      else
        puts "Update didnt finish succesflly"
      end
    end
  end

  def destroy
    @album.destroy
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def album_params
    params.require(:album).permit(:title, :genre_id)
  end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/views/albums/_new.html.erb
<h1>Post Album</h1>

<%= simple_form_for [@artist, @album] do |a| %>
  <%= a.input :title %>
  <%= a.input :genre_id, :as => :hidden, :input_html => {:genre_id => :@genre_id} %>
  <%= a.button :submit %>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit this album</h1>

<%= simple_form_for [@artist, @album] do |a| %>
  <%= a.input :title %>
  <%= a.association :genre, label_method: :genre_name, value_method: :id %>
  <%= a.button :submit %>
<% end %>

app/views/albums/index.html.erb
<h1>All Albums Of <%= @artist.name %> </h1>

<% if @albums.empty? %>
  <h3> (no albums yet) </h3>
<% end %>

<% @albums.each do |a| %>
  <h3>--<%= a.title %>--</h3>
    <% if current_user.id == a.user_id %>
      <h4><%= link_to "Edit this album", edit_artist_album_path(@artist, a) %></h4>
    <% end %>
  <h4> <%= link_to "<Reviews>", album_reviews_path(a) %> / total: <%= a.reviews.count %></h4>
  <h4> <%= link_to "<Songs>", album_songs_path(a) %> / total: <%= a.songs.count %></h4>
<% end %>

<%= render "new", artist: @artist %>

<%= link_to 'Home', root_path %>

app/views/albums/new.html.erb
<h1>Post Album</h1>

<%= simple_form_for [@artist, @album] do |a| %>
  <%= a.input :title %>
  <%= a.input :genre_id, :as => :hidden, :input_html => {:genre_id => :@genre_id} %>
  <%= a.button :submit %>
<% end %>

app/views/albums/show.html.erb
<h1>All Songs Of This Album</h1>

<% @album.songs.each do |a| %>
  <h3><%= a.title %></h3>
<% end %>

<%= link_to 'Post Songs', new_album_song_path(@album_id) %> <br>
<%= link_to 'Home', root_path %>